package org.example;

import org.example.refactoring.EmailSender;
import org.example.refactoring.NotificationSender;
import org.example.refactoring.NotificationService;

/**
 * Code Smell: Concrete Dependency
 * Category: Dependencies
 *
 * Description:
 * The class NotificationService depends directly on the concrete class EmailSender.
 * The dependency is instantiated internally using the 'new' keyword.
 * This design reduces flexibility and violates the Dependency Inversion Principle (DIP),
 * because replacing EmailSender with another notification mechanism would require
 * modifying NotificationService.
 *
 * Expected refactoring:
 * - Introduce an abstraction (e.g. NotificationSender interface)
 * - Make NotificationService depend on the abstraction
 * - Inject the dependency via constructor or setter (Dependency Injection)
 *
 * Program creation:
 * This program was implemented with the help of a Large Language Model (ChatGPT).
 * The initial version generated by the LLM was functional and correctly illustrated
 * the Concrete Dependency code smell.
 * Minor manual adjustments were made to structure the code into a single package
 * and to add explicit comments explaining the design flaw.
 */

//class EmailSender implements NotificationSender {
//    @Override
//    public void sendEmail(String recipient, String message) {
//        System.out.println("[EMAIL] Sending to " + recipient + ": " + message);
//    }
//}

//class NotificationService {
//
//    // Concrete dependency (code smell)
//    private EmailSender emailSender = new EmailSender();
//
//    public void notifyUser(String userEmail, String content) {
//        emailSender.sendEmail(userEmail, content);
//    }
//}
public class Main {
    /**
     * Test method
     * Verifies that NotificationService works correctly
     * despite the presence of a design flaw.
     */
    public static void main(String[] args) {

        NotificationSender emailSender = new EmailSender();
        NotificationService service = new NotificationService(emailSender);

        System.out.println("---- Test NotificationService (IntelliJ refactoring) ----");

        service.notifyUser("user@example.com", "Bienvenue sur notre plateforme !");
        service.notifyUser("admin@example.com", "Un nouvel utilisateur vient de s'inscrire.");
    }
}
