package org.example.initial;

/**
 * Code Smell: Concrete Dependency
 * Category: Dependencies
 *
 * Description:
 * The class NotificationService depends directly on the concrete class EmailSender.
 * The dependency is instantiated internally using the 'new' keyword.
 * This design reduces flexibility and violates the Dependency Inversion Principle (DIP),
 * because replacing EmailSender with another notification mechanism would require
 * modifying NotificationService.
 *
 * Expected refactoring:
 * - Introduce an abstraction (e.g. NotificationSender interface)
 * - Make NotificationService depend on the abstraction
 * - Inject the dependency via constructor or setter (Dependency Injection)
 *
 * Program creation:
 * This program was implemented with the help of a Large Language Model (ChatGPT).
 * The initial version generated by the LLM was functional and correctly illustrated
 * the Concrete Dependency code smell.
 * Minor manual adjustments were made to structure the code into a single package
 * and to add explicit comments explaining the design flaw.
 */


class EmailSender {
    public void sendEmail(String recipient, String message) {
        System.out.println("[EMAIL] Sending to " + recipient + ": " + message);
    }
}

class NotificationService {

    // Code smell: Dépendance directe à une classe concrète (EmailSender)
    private EmailSender emailSender = new EmailSender();

    public void notifyUser(String userEmail, String content) {
        emailSender.sendEmail(userEmail, content);
    }
}
public class Main {
    public static void main(String[] args) {
        NotificationService service = new NotificationService();

        System.out.println("---- Test NotificationService ----");

        service.notifyUser("user@example.com", "Bienvenue sur notre plateforme !");
        service.notifyUser("admin@example.com", "Un nouvel utilisateur vient de s'inscrire.");
    }
}
